import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase-admin'
import type { RegulatoryRequirement } from '@/lib/supabase'

const RISK_ORDER: Record<string, number> = { HIGH: 0, MODERATE: 1, LOW: 2, UNKNOWN: 3 }

// Dynamic import to avoid issues in edge runtime
async function buildPDF(requirements: RegulatoryRequirement[], meta: {
  countries: string[]
  products: string[]
  generatedAt: string
}) {
  const {
    Document,
    Page,
    Text,
    View,
    StyleSheet,
    renderToBuffer,
  } = await import('@react-pdf/renderer')
  const { createElement: h } = await import('react')

  const styles = StyleSheet.create({
    page: { fontFamily: 'Helvetica', padding: 48, fontSize: 10, color: '#111827' },
    header: { marginBottom: 24 },
    title: { fontSize: 18, fontWeight: 'bold', marginBottom: 4 },
    subtitle: { fontSize: 10, color: '#6B7280', marginBottom: 2 },
    disclaimer: {
      fontSize: 8, color: '#9CA3AF', marginTop: 4,
      borderTopWidth: 0.5, borderTopColor: '#E5E7EB', paddingTop: 4,
    },
    sectionLabel: {
      fontSize: 8, fontWeight: 'bold', textTransform: 'uppercase',
      letterSpacing: 1, color: '#6B7280', marginTop: 20, marginBottom: 8,
      borderBottomWidth: 0.5, borderBottomColor: '#E5E7EB', paddingBottom: 4,
    },
    row: {
      flexDirection: 'row', paddingVertical: 10,
      borderBottomWidth: 0.5, borderBottomColor: '#F3F4F6',
    },
    colCountry: { width: 60, fontSize: 9 },
    colProduct: { width: 80, fontSize: 9, color: '#374151' },
    colRisk: { width: 60, fontSize: 9 },
    colSummary: { flex: 1, fontSize: 9, color: '#374151' },
    citation: { fontSize: 7, color: '#9CA3AF', marginTop: 2 },
    verified: { fontSize: 7, color: '#9CA3AF', marginTop: 2 },
    riskHigh: { color: '#EF4444', fontWeight: 'bold' },
    riskModerate: { color: '#F59E0B', fontWeight: 'bold' },
    riskLow: { color: '#10B981', fontWeight: 'bold' },
  })

  const riskStyle = (level: string) => {
    if (level === 'HIGH') return styles.riskHigh
    if (level === 'MODERATE') return styles.riskModerate
    return styles.riskLow
  }

  const grouped: Record<string, RegulatoryRequirement[]> = { HIGH: [], MODERATE: [], LOW: [], UNKNOWN: [] }
  for (const req of requirements) {
    grouped[req.risk_level]?.push(req)
  }

  const doc = h(Document, {},
    h(Page, { size: 'A4', style: styles.page },
      // Header
      h(View, { style: styles.header },
        h(Text, { style: styles.title }, 'Regulatory Compass ASEAN — Regulatory Dossier'),
        h(Text, { style: styles.subtitle },
          `${meta.countries.join(' · ')}  ·  ${meta.products.join(' · ')}`
        ),
        h(Text, { style: styles.subtitle }, `Generated ${new Date(meta.generatedAt).toLocaleDateString('en-SG', { day: 'numeric', month: 'long', year: 'numeric' })}`),
        h(Text, { style: styles.disclaimer },
          'Generated by Regulatory Compass ASEAN — Not Legal Advice. Verify with qualified legal counsel before making operational decisions.'
        )
      ),

      // Sections per risk level
      ...(['HIGH', 'MODERATE', 'LOW', 'UNKNOWN'] as const).flatMap(level => {
        const reqs = grouped[level]
        if (!reqs.length) return []
        const label = level === 'HIGH' ? '🔴 HIGH RISK — Operational Blockers'
          : level === 'MODERATE' ? '🟡 MODERATE RISK — Material Compliance Burden'
          : level === 'LOW' ? '🟢 LOW / INFORMATIONAL'
          : 'UNKNOWN RISK'

        return [
          h(Text, { style: styles.sectionLabel }, label),
          ...reqs.map(req => {
            const country = Array.isArray(req.countries) ? req.countries[0] : req.countries
            const product = Array.isArray(req.product_verticals) ? req.product_verticals[0] : req.product_verticals
            return h(View, { key: req.id, style: styles.row },
              h(View, { style: styles.colCountry },
                h(Text, {}, `${country?.flag_emoji ?? ''} ${country?.code ?? ''}`)
              ),
              h(View, { style: styles.colProduct },
                h(Text, {}, product?.name ?? '')
              ),
              h(View, { style: styles.colRisk },
                h(Text, { style: riskStyle(req.risk_level) }, req.risk_level)
              ),
              h(View, { style: styles.colSummary },
                h(Text, {}, req.summary),
                req.citation ? h(Text, { style: styles.citation }, req.citation) : h(Text, {}),
                h(Text, { style: styles.verified },
                  `Last verified: ${new Date(req.last_verified_at).toLocaleDateString('en-SG')}`
                )
              )
            )
          })
        ]
      })
    )
  )

  return renderToBuffer(doc)
}

export async function POST(req: NextRequest) {
  const body = await req.json()
  const countries: string[] = body.countries ?? []
  const products: string[] = body.products ?? []

  if (!countries.length || !products.length) {
    return NextResponse.json({ error: 'countries and products required' }, { status: 400 })
  }

  // Fetch requirements (same logic as /api/dossier GET)
  const { data: countryRows } = await supabaseAdmin
    .from('countries').select('id, code').in('code', countries)
  const { data: productRows } = await supabaseAdmin
    .from('product_verticals').select('id, slug').in('slug', products)

  if (!countryRows?.length || !productRows?.length) {
    return NextResponse.json({ error: 'Invalid filters' }, { status: 400 })
  }

  const { data, error } = await supabaseAdmin
    .from('regulatory_requirements')
    .select(`
      id, risk_level, risk_reason, title, summary,
      citation, source_url, compliance_deadline,
      last_verified_at, last_changed_at, is_stale, effective_date,
      countries:country_id (code, name, flag_emoji),
      regulators:regulator_id (name, acronym, website_url),
      product_verticals:product_vertical_id (slug, name, icon)
    `)
    .in('country_id', countryRows.map(c => c.id))
    .in('product_vertical_id', productRows.map(p => p.id))

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sorted = ((data ?? []) as any[]).sort(
    (a, b) => RISK_ORDER[a.risk_level] - RISK_ORDER[b.risk_level]
  ) as RegulatoryRequirement[]

  const pdfBuffer = await buildPDF(sorted, {
    countries,
    products,
    generatedAt: new Date().toISOString(),
  })

  return new NextResponse(pdfBuffer as unknown as BodyInit, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename="regcompass-dossier.pdf"',
    },
  })
}
